sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run --privileged -it test "service miredo start && ip addr show && curl http://ipv6.root.cz"
