sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run -it test "sudo modprobe ipv6 && sudo dhclient -6 teredo && sudo ifconfig && curl http://ipv6.root.cz"
