sudo: required
language: generic
before_install:
  - sudo apt-get install -y --no-install-recommends miredo
  - sudo modprobe ipv6
  - sudo service miredo start
  - sudo ip addr show
  - cd /etc/modprobe.d
  - grep ipv6 *
  - cat blacklist.local
script:
  - curl http://ipv6.root.cz
